#!/usr/bin/env python3
"""Merge existing Georgia corpus with projects opened/announced Apr–Jul 2026."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data" / "georgia-commercial-projects.json"
PUBLIC = ROOT / "public" / "data" / "georgia-commercial-projects.json"

NEW_PROJECTS = [
    {
        "id": "foundry-at-mosaic-pooler",
        "name": "The Foundry at Mosaic",
        "city": "Pooler",
        "county": "Chatham",
        "status": "under_construction",
        "project_type": "multifamily",
        "estimated_value_usd": None,
        "square_footage": None,
        "owner": "Thompson Thrift",
        "architect": "",
        "general_contractor": "",
        "opened_or_announced_date": "2026-07-20",
        "description": "300-unit luxury apartment community at Mosaic Town Center near I-16 and Pooler Parkway. Construction began July 2026; first move-ins targeted November 2027.",
        "key_specs": ["300 units", "1–3 bedroom plans up to 1,475 SF", "Resort pool, fitness, pickleball, golf simulator", "Near Hyundai Metaplant and Port of Savannah"],
        "mentioned_brands": [],
        "competitor_watch": ["appliance packages", "flooring", "HVAC", "lighting and controls", "plumbing fixtures", "smart-home devices"],
        "sources": [{"title": "citybiz — Thompson Thrift breaks ground", "url": "https://www.citybiz.co/article/876642/thompson-thrift-breaks-ground-on-300-unit-apartment-community-near-savannah/"}],
        "open_for": "Early vertical construction — interior finish and MEP specs still open.",
    },
    {
        "id": "675-morgan-savannah",
        "name": "675 Morgan",
        "city": "Savannah",
        "county": "Chatham",
        "status": "under_construction",
        "project_type": "multifamily",
        "estimated_value_usd": None,
        "square_footage": None,
        "owner": "Manor Park Ventures + Brook Farm Group",
        "architect": "",
        "general_contractor": "Summit Contracting Group",
        "opened_or_announced_date": "2026-06-26",
        "description": "336-unit Class A garden-style community on 27-acre entitled site at Highlands PUD. Broke ground June 2026; completion Q2 2028.",
        "key_specs": ["336 units across 11 three-story buildings", "Resort pool, clubhouse, fitness, pickleball", "Only multifamily parcel in Highlands PUD"],
        "mentioned_brands": [],
        "competitor_watch": ["flooring", "HVAC", "appliances", "lighting", "doors and hardware", "site amenities"],
        "sources": [{"title": "PR Newswire — 675 Morgan groundbreaking", "url": "https://www.prnewswire.com/news-releases/family-office-backed-manor-park-ventures-and-brook-farm-group-break-ground-on-336-unit-community-in-booming-savannah-market-302810774.html"}],
        "open_for": "Just broke ground — prime spec window for interior and MEP packages.",
    },
    {
        "id": "savannah-port-logistics-center",
        "name": "Savannah Port Logistics Center",
        "city": "Savannah",
        "county": "Chatham",
        "status": "under_construction",
        "project_type": "industrial",
        "estimated_value_usd": 125000000,
        "square_footage": 2300000,
        "owner": "Capital Development Partners + Greenfield Partners",
        "architect": "",
        "general_contractor": "",
        "opened_or_announced_date": "2026-06-01",
        "description": "2.3M SF logistics center ~10 miles from Port of Savannah via Highway 80. $125M joint venture; construction began after March 2026 announcement.",
        "key_specs": ["2.3M SF logistics", "$125M investment", "Near Port of Savannah", "Highway 80 access"],
        "mentioned_brands": [],
        "competitor_watch": ["dock equipment", "overhead doors", "high-bay lighting", "roofing", "fire protection", "concrete/paving"],
        "sources": [{"title": "Capital Development Partners", "url": "https://capitaldevelopmentpartners.com/construction-begins-on-125-million-savannah-port-logistics-center/"}],
        "open_for": "Active construction — industrial building product specs in play.",
    },
    {
        "id": "buc-ees-smarr-monroe",
        "name": "Buc-ee's Smarr (Monroe County)",
        "city": "Smarr",
        "county": "Monroe",
        "status": "under_construction",
        "project_type": "retail",
        "estimated_value_usd": None,
        "square_footage": 74000,
        "owner": "Buc-ee's",
        "architect": "",
        "general_contractor": "",
        "opened_or_announced_date": "2026-04-08",
        "description": "74,000 SF travel center at I-75 Exit 181 with 100 fueling positions. Official groundbreaking April 2026; opening targeted late summer 2027.",
        "key_specs": ["74,000 SF", "100 fueling positions", "35-acre site", "200+ jobs"],
        "mentioned_brands": ["Buc-ee's"],
        "competitor_watch": ["fuel systems", "commercial kitchen equipment", "HVAC", "plumbing", "lighting", "paving/site work"],
        "sources": [{"title": "AJC — Another Buc-ee's breaks ground in Georgia", "url": "https://www.ajc.com/news/2026/04/another-buc-ees-breaks-ground-in-georgia-as-locals-roll-out-welcome-mat/"}],
        "open_for": "Site work and building package specs active through 2027 opening.",
    },
    {
        "id": "alta-newnan-crossing",
        "name": "Alta Newnan Crossing",
        "city": "Newnan",
        "county": "Coweta",
        "status": "under_construction",
        "project_type": "mixed_use",
        "estimated_value_usd": None,
        "square_footage": None,
        "owner": "Wood Partners",
        "architect": "",
        "general_contractor": "",
        "opened_or_announced_date": "2026-05-26",
        "description": "274 apartments, 7 townhomes, and 7,700 SF retail. Broke ground May 26, 2026; completion fall 2027.",
        "key_specs": ["274 units + 7 townhomes", "7,700 SF retail", "40 miles SW of Atlanta"],
        "mentioned_brands": [],
        "competitor_watch": ["flooring", "HVAC", "appliances", "retail storefront systems", "lighting"],
        "sources": [{"title": "PR Newswire — Wood Partners Alta Newnan", "url": "https://www.morningstar.com/news/pr-newswire/20260526cl67810/wood-partners-breaks-ground-on-alta-newnan-crossing-in-newnan-georgia"}],
        "open_for": "Ground broken — interior and retail spec packages open.",
    },
    {
        "id": "hampton-inn-kennesaw",
        "name": "Hampton Inn Atlanta Kennesaw NW / Town Center",
        "city": "Kennesaw",
        "county": "Cobb",
        "status": "under_construction",
        "project_type": "hospitality",
        "estimated_value_usd": None,
        "square_footage": None,
        "owner": "Vector Hospitality",
        "architect": "",
        "general_contractor": "Sturgis Construction",
        "opened_or_announced_date": "2026-06-02",
        "description": "123-room Hampton by Hilton off Cobb Place Lane NW. Groundbreaking June 2026; opening summer 2027.",
        "key_specs": ["123 rooms", "Meeting space and fitness", "Near I-75, KSU, Town Center at Cobb"],
        "mentioned_brands": ["Hilton", "Hampton Inn"],
        "competitor_watch": ["guestroom FF&E", "HVAC", "plumbing fixtures", "lighting", "elevators", "commercial laundry"],
        "sources": [{"title": "Hotel Online — Vector Hospitality Kennesaw", "url": "https://www.hotel-online.com/news/vector-hospitality-inc-breaks-ground-on-hampton-inn-by-hilton-atlanta-nw-kennesawtown-center"}],
        "open_for": "New-build hospitality — FF&E and building systems specs open.",
    },
    {
        "id": "candler-crossing",
        "name": "Candler Crossing",
        "city": "Decatur",
        "county": "DeKalb",
        "status": "under_construction",
        "project_type": "retail",
        "estimated_value_usd": 28900000,
        "square_footage": 61525,
        "owner": "Venture South Investments",
        "architect": "",
        "general_contractor": "",
        "opened_or_announced_date": "2026-06-11",
        "description": "$28.9M mixed-use retail at Candler & Glenwood Roads: 50,325 SF Publix anchor, 11,200 SF multi-tenant retail, plaza and trail. Broke ground June 11, 2026.",
        "key_specs": ["50,325 SF Publix", "11,200 SF multi-tenant retail", "Community plaza and walking trail", "183 permanent jobs"],
        "mentioned_brands": ["Publix"],
        "competitor_watch": ["refrigeration", "HVAC", "storefront systems", "lighting", "flooring", "paving"],
        "sources": [{"title": "Decide DeKalb — Candler Crossing", "url": "https://www.decidedekalb.com/news/decide-dekalb-and-venture-south-investments-break-ground-on-28-9-million-mixed-use-development-on-candler-road/"}],
        "open_for": "Construction started June 2026 — tenant build-out and anchor specs active.",
    },
    {
        "id": "macon-arena",
        "name": "New Macon Arena",
        "city": "Macon",
        "county": "Bibb",
        "status": "under_construction",
        "project_type": "civic",
        "estimated_value_usd": 350000000,
        "square_footage": 230000,
        "owner": "Macon-Bibb County",
        "architect": "PBK Architects",
        "general_contractor": "Barton Malow + Sheridan Construction",
        "opened_or_announced_date": "2026-07-01",
        "description": "230,000+ SF multi-purpose arena replacing Macon Coliseum. Up to 12,298 center-stage capacity. Groundbreaking late July 2026; opening late 2028.",
        "key_specs": ["230,000+ SF", "12,298 center-stage capacity", "300-space VIP parking deck + 500-space lot", "Phased construction while Coliseum operates"],
        "mentioned_brands": [],
        "competitor_watch": ["arena seating", "HVAC", "acoustics", "lighting and controls", "AV systems", "flooring", "egress hardware"],
        "sources": [{"title": "Macon Telegraph — arena design reveal", "url": "https://www.macon.com/news/local/article316247768.html"}],
        "open_for": "Groundbreaking July 2026 — major MEP and interior packages ahead.",
    },
    {
        "id": "costco-macon",
        "name": "Costco Wholesale Macon",
        "city": "Macon",
        "county": "Bibb",
        "status": "permitting",
        "project_type": "retail",
        "estimated_value_usd": None,
        "square_footage": 158000,
        "owner": "Costco",
        "architect": "",
        "general_contractor": "",
        "opened_or_announced_date": "2026-06-01",
        "description": "158,000 SF warehouse club at Bass Road and new Forsyth Road with 32-pump gas station. P&Z approved; opening summer 2027.",
        "key_specs": ["158,000 SF warehouse", "32-pump gas station", "North Macon location"],
        "mentioned_brands": ["Costco"],
        "competitor_watch": ["refrigeration", "HVAC", "dock doors", "lighting", "fuel systems", "concrete/paving"],
        "sources": [{"title": "41NBC — Costco approved for Macon", "url": "https://www.41nbc.com/coming-soon-new-costco-approved-for-macon/"}],
        "open_for": "Approved for development — specs and GC packages forming.",
    },
    {
        "id": "arcelormittal-macon-hq",
        "name": "ArcelorMittal Building Solutions HQ & Manufacturing",
        "city": "Macon",
        "county": "Bibb",
        "status": "planning",
        "project_type": "industrial",
        "estimated_value_usd": 57000000,
        "square_footage": None,
        "owner": "ArcelorMittal Building Solutions",
        "architect": "",
        "general_contractor": "",
        "opened_or_announced_date": "2026-06-01",
        "description": "North American HQ and manufacturing at Airport South Industrial Park. $57M initial investment, up to 70 jobs; construction H2 2026, operations H2 2027.",
        "key_specs": ["HQ + manufacturing + training facility", "Building enclosure products", "Airport South Industrial Park"],
        "mentioned_brands": ["ArcelorMittal"],
        "competitor_watch": ["metal building systems", "insulation", "HVAC", "industrial doors", "lighting", "fire protection"],
        "sources": [{"title": "Georgia DED — ArcelorMittal Macon", "url": "https://topstatefortalent.georgia.gov/news/2026-06-01/gov-kemp-arcelormittal-building-solutions-brings-north-american-hq-macon-bibb"}],
        "open_for": "Pre-construction H2 2026 — industrial and enclosure specs open.",
    },
    {
        "id": "project-azalea-thomson",
        "name": "Project Azalea Data Center",
        "city": "Thomson",
        "county": "McDuffie",
        "status": "permitting",
        "project_type": "industrial",
        "estimated_value_usd": 1000000000,
        "square_footage": None,
        "owner": "Project Turbo LLC",
        "architect": "",
        "general_contractor": "",
        "opened_or_announced_date": "2026-03-18",
        "description": "200-acre, six-building data center campus approved March 2026 near Augusta. ~400MW Jefferson Energy supply; completion target 2029 pending power upgrades.",
        "key_specs": ["Six data center buildings", "200 acres", "400MW energy load", "Own substation and backup generation"],
        "mentioned_brands": [],
        "competitor_watch": ["switchgear", "generators", "cooling systems", "fire suppression", "security systems", "raised floor"],
        "sources": [{"title": "Data Center Dynamics — Project Azalea", "url": "https://www.datacenterdynamics.com/en/news/200-acre-project-azalea-data-center-approved/"}],
        "open_for": "Approved — design and MEP specs forming ahead of construction.",
    },
    {
        "id": "teachers-village-atlanta",
        "name": "Teachers Village",
        "city": "Atlanta",
        "county": "Fulton",
        "status": "under_construction",
        "project_type": "mixed_use",
        "estimated_value_usd": 77125000,
        "square_footage": None,
        "owner": "Invest Atlanta / developer consortium",
        "architect": "",
        "general_contractor": "",
        "opened_or_announced_date": "2026-03-19",
        "description": "33-story affordable housing tower in Fairlie-Poplar Historic District. $77.1M building permit March 19, 2026; workforce and senior units plus retail.",
        "key_specs": ["33 stories", "Income-restricted apartments", "Workforce housing for teachers", "Senior independent living units", "Retail + parking"],
        "mentioned_brands": [],
        "competitor_watch": ["HVAC", "elevators", "flooring", "kitchen/bath packages", "lighting", "fire/life safety"],
        "sources": [{"title": "BLDUP — Teachers Village permit", "url": "https://www.bldup.com/posts/atlanta-s-33-story-affordable-housing-tower-secures-77m-building-permit-signaling-vertical-construction"}],
        "open_for": "Vertical construction starting — high-rise MEP and interior specs open.",
    },
    {
        "id": "novel-lulah-hills",
        "name": "Novel Lulah Hills",
        "city": "Decatur",
        "county": "DeKalb",
        "status": "under_construction",
        "project_type": "mixed_use",
        "estimated_value_usd": 81845000,
        "square_footage": 259099,
        "owner": "Crescent Communities / EDENS / NTT Urban Development",
        "architect": "",
        "general_contractor": "Fortune-Johnson",
        "opened_or_announced_date": "2026-03-01",
        "description": "303-unit six-story multifamily with 39,000 SF ground-floor retail at former North DeKalb Mall site. Broke ground March 2026; move-ins late 2027.",
        "key_specs": ["303 units", "39,000 SF retail", "Part of 78-acre Lulah Hills redevelopment", "1,800 units planned at full build-out"],
        "mentioned_brands": [],
        "competitor_watch": ["curtain wall", "HVAC", "flooring", "appliances", "retail storefront", "lighting"],
        "sources": [{"title": "Multi-Housing News — Novel Lulah Hills", "url": "https://www.multihousingnews.com/crescent-communities-breaks-ground-on-suburban-atlanta-multifamily/"}],
        "open_for": "First vertical at Lulah Hills — specs active for residential and retail podiums.",
    },
    {
        "id": "overlook-at-garson",
        "name": "The Overlook at Garson",
        "city": "Atlanta",
        "county": "Fulton",
        "status": "under_construction",
        "project_type": "mixed_use",
        "estimated_value_usd": None,
        "square_footage": None,
        "owner": "Pennrose",
        "architect": "Smith Dalia Architects",
        "general_contractor": "McShane Construction",
        "opened_or_announced_date": "2026-07-01",
        "description": "130 workforce apartments and 10,300 SF Beltline-level retail on Garson Drive NE. Construction began mid-2026; opening May 2028.",
        "key_specs": ["130 affordable units (30–80% AMI)", "10,300 SF commercial at Beltline level", "100-space parking garage", "Adjacent to Northeast Trail"],
        "mentioned_brands": ["GE"],
        "competitor_watch": ["appliances", "HVAC", "flooring", "lighting", "storefront systems", "plumbing fixtures"],
        "sources": [{"title": "Rough Draft Atlanta — Overlook at Garson", "url": "https://roughdraftatlanta.com/2026/07/20/garson-drive-development-completion-2028/"}],
        "open_for": "Active construction — interior and amenity specs open.",
    },
    {
        "id": "sr-400-express-lanes",
        "name": "SR 400 Express Lanes (Peach Partners P3)",
        "city": "Atlanta",
        "county": "Fulton",
        "status": "under_construction",
        "project_type": "civic",
        "estimated_value_usd": 4600000000,
        "square_footage": None,
        "owner": "Georgia DOT / SR 400 Peach Partners",
        "architect": "",
        "general_contractor": "FlatironDragados + Acciona",
        "opened_or_announced_date": "2026-04-22",
        "description": "$4.6B construction ($10.8B total program) adding tolled express lanes on ~16 miles of SR 400 from Fulton to Forsyth. Broke ground April 22, 2026.",
        "key_specs": ["~16 miles express lanes", "I-285/SR 400 interchange improvements", "Dynamic tolling", "P3 design-build"],
        "mentioned_brands": [],
        "competitor_watch": ["traffic systems", "lighting", "barriers/guardrail", "electrical", "signage", "paving materials"],
        "sources": [{"title": "Construction Dive — SR 400 Express Lanes", "url": "https://www.constructiondive.com/news/flatiron-dragados-acciona-p3-highway-georgia-400/818597/"}],
        "open_for": "Major civil package underway — infrastructure product specs active.",
    },
    {
        "id": "motto-hilton-midtown",
        "name": "Motto by Hilton Midtown Atlanta",
        "city": "Atlanta",
        "county": "Fulton",
        "status": "under_construction",
        "project_type": "hospitality",
        "estimated_value_usd": 34100000,
        "square_footage": None,
        "owner": "",
        "architect": "",
        "general_contractor": "",
        "opened_or_announced_date": "2026-07-10",
        "description": "12-story Motto by Hilton at 512 West Peachtree NW. $34.1M permit issued July 2026 — Georgia's first Motto flag.",
        "key_specs": ["12 stories", "512 W Peachtree St NW", "$34.1M permit value"],
        "mentioned_brands": ["Hilton", "Motto"],
        "competitor_watch": ["guestroom FF&E", "HVAC", "plumbing", "lighting", "elevators"],
        "sources": [{"title": "BLDUP — Motto Midtown", "url": "https://www.bldup.com/projects/motto-downtown-atlanta"}],
        "open_for": "Permit issued July 2026 — hospitality build-out specs open.",
    },
    {
        "id": "towneplace-suites-midtown",
        "name": "TownePlace Suites Midtown Atlanta",
        "city": "Atlanta",
        "county": "Fulton",
        "status": "under_construction",
        "project_type": "hospitality",
        "estimated_value_usd": 30200000,
        "square_footage": None,
        "owner": "",
        "architect": "",
        "general_contractor": "",
        "opened_or_announced_date": "2026-07-10",
        "description": "12-story extended-stay hotel at 526 West Peachtree NW. $30.2M permit July 2026.",
        "key_specs": ["12 stories", "Extended-stay hotel", "526 W Peachtree St NW"],
        "mentioned_brands": ["Marriott", "TownePlace Suites"],
        "competitor_watch": ["kitchen packages", "HVAC", "plumbing fixtures", "lighting", "FF&E"],
        "sources": [{"title": "BLDUP — TownePlace Midtown", "url": "https://www.bldup.com/projects/526-west-peachtree-street-northwest"}],
        "open_for": "Permit issued — extended-stay FF&E and systems specs open.",
    },
    {
        "id": "virgin-hotel-centennial-yards",
        "name": "Virgin Hotel Centennial Yards",
        "city": "Atlanta",
        "county": "Fulton",
        "status": "planning",
        "project_type": "hospitality",
        "estimated_value_usd": None,
        "square_footage": None,
        "owner": "CIM Group / Centennial Yards Company / Drew Company",
        "architect": "",
        "general_contractor": "",
        "opened_or_announced_date": "2026-04-22",
        "description": "Virgin Hotels lifestyle flag announced for Centennial Yards Entertainment District. 2027 debut alongside Live Nation and Cosm venues.",
        "key_specs": ["Virgin Hotels flag", "Centennial Yards Entertainment District", "2027 target opening"],
        "mentioned_brands": ["Virgin Hotels"],
        "competitor_watch": ["guestroom FF&E", "HVAC", "lighting", "plumbing", "AV systems"],
        "sources": [{"title": "Business Wire — Virgin Hotel Atlanta", "url": "https://www.businesswire.com/news/home/20260422617909/en/CIM-Group-Centennial-Yards-Company-and-The-Drew-Company-Announce-Partnership-to-Bring-Award-Winning-Virgin-Hotel-to-Downtown-Atlanta"}],
        "open_for": "Pre-construction design — hospitality and entertainment district specs forming.",
    },
    {
        "id": "continuum-alpharetta",
        "name": "Continuum Alpharetta",
        "city": "Alpharetta",
        "county": "Fulton",
        "status": "under_construction",
        "project_type": "mixed_use",
        "estimated_value_usd": None,
        "square_footage": 99058,
        "owner": "",
        "architect": "",
        "general_contractor": "",
        "opened_or_announced_date": "2026-01-01",
        "description": "52-acre mixed-use: 280 luxury apartments, 98 townhomes, 74,000 SF retail, and 808,000 SF future office at 5555 Windward Pkwy. Residential breaking ground 2026.",
        "key_specs": ["280 apartments + 98 townhomes", "74,000 SF retail", "515,438 SF renovated office (Aug 2025)", "808,000 SF BTS office available"],
        "mentioned_brands": [],
        "competitor_watch": ["curtain wall", "HVAC", "flooring", "retail storefront", "lighting", "paving"],
        "sources": [{"title": "Continuum Alpharetta property report", "url": "https://properties.zoomprospector.com/statega/property/5555-Windward-Pkwy-Alpharetta-Georgia/8486F35A-71DE-4683-8E5E-7C944004D778"}],
        "open_for": "Residential phase starting 2026 — multifamily and retail specs open.",
    },
    {
        "id": "hyundai-sk-battery-bartow",
        "name": "Hyundai-SK Battery Plant (Bartow County)",
        "city": "Adairsville area",
        "county": "Bartow",
        "status": "under_construction",
        "project_type": "industrial",
        "estimated_value_usd": 5000000000,
        "square_footage": None,
        "owner": "Hyundai-SK Battery Manufacturing America",
        "architect": "",
        "general_contractor": "",
        "opened_or_announced_date": "2026-06-01",
        "description": "$5B joint venture battery cell plant on ~752 acres. Production began June 2026 ramping to 35 GWh/year (~300k EVs). Supplies Hyundai Metaplant.",
        "key_specs": ["35 GWh annual capacity", "752-acre site", "3,500+ jobs", "EV battery cells"],
        "mentioned_brands": ["Hyundai", "SK On"],
        "competitor_watch": ["process HVAC", "fire suppression", "electrical/switchgear", "cleanroom systems", "industrial flooring"],
        "sources": [{"title": "AJC — Hyundai-SK battery plant opens", "url": "https://www.ajc.com/business/2026/07/sk-and-hyundai-open-new-5b-ev-battery-plant-northwest-of-atlanta/"}],
        "open_for": "Early production ramp — process and industrial support specs may still shift.",
    },
    {
        "id": "hyundai-lg-battery-metaplant",
        "name": "Hyundai-LG Battery Plant (Metaplant Campus)",
        "city": "Ellabell area",
        "county": "Bryan",
        "status": "under_construction",
        "project_type": "industrial",
        "estimated_value_usd": 4000000000,
        "square_footage": 2500000,
        "owner": "Hyundai + LG Energy Solution",
        "architect": "",
        "general_contractor": "",
        "opened_or_announced_date": "2026-04-15",
        "description": "2.5M SF battery factory on Metaplant campus. Opening April 2026 after ICE-related delay; 500+ employees.",
        "key_specs": ["2.5M SF", "On Metaplant America campus", "500+ employees", "EV battery production"],
        "mentioned_brands": ["Hyundai", "LG Energy Solution"],
        "competitor_watch": ["process HVAC", "fire suppression", "electrical", "cleanroom/industrial systems"],
        "sources": [{"title": "AJC — Hyundai LG battery plant opening", "url": "https://www.ajc.com/business/2026/04/hyundai-battery-plant-in-georgia-set-to-open-months-after-ice-raid/"}],
        "open_for": "Commissioning phase — late add-ons and support systems possible.",
    },
    {
        "id": "centennial-yards-hotel-interior",
        "name": "Centennial Yards Building C Hotel Interior",
        "city": "Atlanta",
        "county": "Fulton",
        "status": "under_construction",
        "project_type": "hospitality",
        "estimated_value_usd": 40000000,
        "square_footage": 195061,
        "owner": "Centennial Yards Company",
        "architect": "",
        "general_contractor": "",
        "opened_or_announced_date": "2026-03-03",
        "description": "$40M interior fit-out permit March 2026 for high-rise hotel at 85 Centennial Olympic Park Drive (Building C).",
        "key_specs": ["195,061 SF interior fit-out", "Building C hotel tower", "Entertainment District"],
        "mentioned_brands": [],
        "competitor_watch": ["FF&E", "HVAC", "lighting", "plumbing fixtures", "AV", "elevators"],
        "sources": [{"title": "BLDUP — Centennial Yards hotel interior", "url": "https://www.bldup.com/posts/atlanta-s-centennial-yards-entertainment-district-surges-forward-with-40m-hotel-interior-milestone"}],
        "open_for": "Interior fit-out active — hospitality finish specs in play.",
    },
    {
        "id": "centennial-yards-elliott-hotel",
        "name": "Centennial Yards Elliott Street Boutique Hotel",
        "city": "Atlanta",
        "county": "Fulton",
        "status": "permitting",
        "project_type": "hospitality",
        "estimated_value_usd": None,
        "square_footage": None,
        "owner": "Centennial Yards Company",
        "architect": "Praxis 3",
        "general_contractor": "",
        "opened_or_announced_date": "2026-07-01",
        "description": "Four-story boutique hotel with 141 keys along Elliott Street. Land disturbance permit filed; construction targeted Q4 2026.",
        "key_specs": ["141 hotel keys", "4 stories", "Praxis 3 design", "No required parking (MARTA proximity)"],
        "mentioned_brands": [],
        "competitor_watch": ["guestroom FF&E", "HVAC", "lighting", "plumbing", "storefront/entry systems"],
        "sources": [{"title": "Urbanize Atlanta — Elliott Street hotel", "url": "https://atlanta.urbanize.city/post/centennial-yards-gulch-new-hotel-moving-forward-downtown-images"}],
        "open_for": "Permitting/pre-construction — specs forming for Q4 2026 start.",
    },
    {
        "id": "monroe-drive-safe-streets",
        "name": "Monroe Drive Safe Streets Project",
        "city": "Atlanta",
        "county": "Fulton",
        "status": "under_construction",
        "project_type": "civic",
        "estimated_value_usd": None,
        "square_footage": None,
        "owner": "City of Atlanta",
        "architect": "",
        "general_contractor": "",
        "opened_or_announced_date": "2026-07-22",
        "description": "City of Atlanta Safe Streets infrastructure project on Monroe Drive. Groundbreaking July 22, 2026.",
        "key_specs": ["Complete Streets improvements", "Monroe Drive corridor", "Pedestrian/cyclist safety"],
        "mentioned_brands": [],
        "competitor_watch": ["paving", "lighting", "signage", "stormwater", "site furnishings"],
        "sources": [{"title": "City of Atlanta — Monroe Drive Safe Streets", "url": "https://www.atlantaga.gov/"}],
        "open_for": "Just broke ground — civil and site product specs active.",
    },
    {
        "id": "mercer-med-school-macon-riverfront",
        "name": "Mercer School of Medicine Riverfront Campus",
        "city": "Macon",
        "county": "Bibb",
        "status": "under_construction",
        "project_type": "education",
        "estimated_value_usd": 80000000,
        "square_footage": None,
        "owner": "Mercer University",
        "architect": "McMillan Pazdan Smith",
        "general_contractor": "Sheridan Construction",
        "opened_or_announced_date": "2025-11-07",
        "description": "$80M medical school building plus lofts, retail, and parking along Ocmulgee River. Active construction; opening fall 2028.",
        "key_specs": ["$80M med school building", "Lofts + retail + parking decks", "Gateway to downtown Macon", "Part of ~$400M riverfront investment"],
        "mentioned_brands": [],
        "competitor_watch": ["lab casework", "HVAC/lab air", "flooring", "lighting", "medical gas", "doors and hardware"],
        "sources": [{"title": "Mercer — med school groundbreaking", "url": "https://den.mercer.edu/mercer-breaks-ground-on-new-medical-school-building-in-downtown-macon/"}],
        "open_for": "Active construction — lab and institutional specs still open.",
    },
    {
        "id": "macon-convention-center-hotel",
        "name": "Macon Convention Center & Hotel",
        "city": "Macon",
        "county": "Bibb",
        "status": "planning",
        "project_type": "mixed_use",
        "estimated_value_usd": None,
        "square_footage": None,
        "owner": "Macon-Bibb County",
        "architect": "",
        "general_contractor": "",
        "opened_or_announced_date": "2026-06-01",
        "description": "Planned convention center and adjoining hotel at 108 First Street (former Ramada site). Part of $1B+ riverfront/arena district investment.",
        "key_specs": ["Convention center", "Adjoining hotel", "108 First Street site", "Near new arena and Mercer med school"],
        "mentioned_brands": [],
        "competitor_watch": ["HVAC", "AV/conference systems", "FF&E", "lighting", "flooring", "kitchen equipment"],
        "sources": [{"title": "Mercer / Macon riverfront coverage", "url": "https://den.mercer.edu/mercer-breaks-ground-on-new-medical-school-building-in-downtown-macon/"}],
        "open_for": "Planning phase — early specs and design partnerships open.",
    },
    {
        "id": "campus-244-dunwoody",
        "name": "Campus 244 Expansion",
        "city": "Dunwoody",
        "county": "DeKalb",
        "status": "planning",
        "project_type": "mixed_use",
        "estimated_value_usd": None,
        "square_footage": 200000,
        "owner": "",
        "architect": "",
        "general_contractor": "",
        "opened_or_announced_date": "2026-06-01",
        "description": "Proposed expansion: 150-room hotel, 200,000 SF office, and 350 apartments at Campus 244. Rezoning pending mid-2026.",
        "key_specs": ["150-room hotel", "200,000 SF office", "350 apartments", "Perimeter Center submarket"],
        "mentioned_brands": [],
        "competitor_watch": ["curtain wall", "HVAC", "elevators", "flooring", "lighting", "hotel FF&E"],
        "sources": [{"title": "Atlanta commercial development coverage", "url": "https://www.bisnow.com/atlanta/"}],
        "open_for": "Rezoning/planning — influence specs before entitlement completes.",
    },
    {
        "id": "pnk-griffin-200",
        "name": "PNK Griffin 200",
        "city": "Griffin",
        "county": "Spalding",
        "status": "under_construction",
        "project_type": "industrial",
        "estimated_value_usd": None,
        "square_footage": 1000000,
        "owner": "PNK Group",
        "architect": "",
        "general_contractor": "",
        "opened_or_announced_date": "2026-05-26",
        "description": "1M SF speculative industrial at 35 S. McDonough Road using PNK BAS prefab technology. Construction began May 26, 2026.",
        "key_specs": ["1M SF speculative", "40' clear heights", "194 dock doors", "185' truck court", "PNK BAS prefab"],
        "mentioned_brands": [],
        "competitor_watch": ["dock equipment", "overhead doors", "high-bay lighting", "roofing", "fire protection", "concrete"],
        "sources": [{"title": "REBusinessOnline — PNK Griffin 200", "url": "https://rebusinessonline.com/pnk-group-begins-construction-on-1-msf-industrial-facility-in-griffin-georgia/"}],
        "open_for": "Just started — industrial shell and systems specs open.",
    },
    {
        "id": "scannell-ridgeway-phase-1",
        "name": "Ridgeway Logistics Park Phase I",
        "city": "Ellabell",
        "county": "Bryan",
        "status": "under_construction",
        "project_type": "industrial",
        "estimated_value_usd": None,
        "square_footage": 1100000,
        "owner": "Scannell Properties",
        "architect": "",
        "general_contractor": "",
        "opened_or_announced_date": "2026-06-01",
        "description": "1.1M SF speculative industrial across from Hyundai Metaplant. Site work began summer 2026 on 335-acre park (up to 4M SF build-out).",
        "key_specs": ["1.1M SF Phase I", "40' clear heights", "234 dock positions", "Adjacent to I-16 interchange"],
        "mentioned_brands": [],
        "competitor_watch": ["dock equipment", "overhead doors", "lighting", "roofing", "fire protection"],
        "sources": [{"title": "REBusinessOnline — Ridgeway Logistics Park", "url": "https://rebusinessonline.com/scannell-properties-to-develop-335-acre-logistics-park-near-savannah/"}],
        "open_for": "Site work started — industrial building product specs active.",
    },
    {
        "id": "dodge-data-center-clayton",
        "name": "Clayton County Data Center (DRI filed)",
        "city": "Clayton County",
        "county": "Clayton",
        "status": "planning",
        "project_type": "industrial",
        "estimated_value_usd": None,
        "square_footage": None,
        "owner": "",
        "architect": "",
        "general_contractor": "",
        "opened_or_announced_date": "2026-07-22",
        "description": "Data center DRI form filed July 2026 in Clayton County alongside OpenAI Effingham and Troup County projects.",
        "key_specs": ["Data center campus", "DRI evaluation pending", "South metro Atlanta"],
        "mentioned_brands": [],
        "competitor_watch": ["switchgear", "generators", "cooling", "fire suppression", "security"],
        "sources": [{"title": "The Current GA — data center DRIs", "url": "https://thecurrentga.org/2026/07/22/20-billion-openai-data-center-to-open-in-effingham-county/"}],
        "open_for": "Early planning — design partnerships open.",
    },
    {
        "id": "troup-county-data-center",
        "name": "Troup County Data Center (DRI filed)",
        "city": "Troup County",
        "county": "Troup",
        "status": "planning",
        "project_type": "industrial",
        "estimated_value_usd": None,
        "square_footage": None,
        "owner": "",
        "architect": "",
        "general_contractor": "",
        "opened_or_announced_date": "2026-07-22",
        "description": "Data center Development of Regional Impact filing July 2026 in Troup County (west Georgia).",
        "key_specs": ["Data center DRI", "West Georgia location", "Evaluation pending"],
        "mentioned_brands": [],
        "competitor_watch": ["switchgear", "generators", "cooling systems", "fire suppression"],
        "sources": [{"title": "The Current GA — data center DRIs", "url": "https://thecurrentga.org/2026/07/22/20-billion-openai-data-center-to-open-in-effingham-county/"}],
        "open_for": "Pre-development — early MEP and infrastructure specs.",
    },
    {
        "id": "master-wall-columbus-hq",
        "name": "Master Wall Columbus HQ Expansion",
        "city": "Columbus",
        "county": "Muscogee",
        "status": "under_construction",
        "project_type": "industrial",
        "estimated_value_usd": 7000000,
        "square_footage": 46500,
        "owner": "Master Wall Inc.",
        "architect": "",
        "general_contractor": "",
        "opened_or_announced_date": "2026-04-01",
        "description": "$7M corporate headquarters expansion in Columbus for exterior insulation and finish systems manufacturer.",
        "key_specs": ["46,500 SF expansion", "EIFS/stucco systems manufacturer HQ", "Columbus metro"],
        "mentioned_brands": ["Master Wall"],
        "competitor_watch": ["EIFS/stucco systems", "insulation", "HVAC", "metal studs", "coatings"],
        "sources": [{"title": "Columbus GA commercial development coverage", "url": "https://rebusinessonline.com/"}],
        "open_for": "Expansion underway — building envelope product specs relevant.",
    },
    {
        "id": "white-oak-technology-park",
        "name": "White Oak Technology Park",
        "city": "Augusta area",
        "county": "Columbia",
        "status": "planning",
        "project_type": "industrial",
        "estimated_value_usd": None,
        "square_footage": 8000000,
        "owner": "",
        "architect": "",
        "general_contractor": "",
        "opened_or_announced_date": "2026-05-01",
        "description": "Plans filed for 8M SF technology/industrial park in Columbia County near Augusta — one of largest proposed industrial developments in the region.",
        "key_specs": ["Up to 8M SF", "Technology/industrial park", "Columbia County / Augusta metro"],
        "mentioned_brands": [],
        "competitor_watch": ["site infrastructure", "utility systems", "prefab industrial", "data center shells"],
        "sources": [{"title": "Augusta area development coverage", "url": "https://augustagoodnews.com/"}],
        "open_for": "Master planning — early infrastructure and shell specs.",
    },
    {
        "id": "augusta-dental-college-savannah",
        "name": "Dental College of Georgia — Savannah Campus",
        "city": "Savannah",
        "county": "Chatham",
        "status": "under_construction",
        "project_type": "education",
        "estimated_value_usd": None,
        "square_footage": None,
        "owner": "Augusta University / Dental College of Georgia",
        "architect": "",
        "general_contractor": "",
        "opened_or_announced_date": "2026-04-01",
        "description": "New Dental College of Georgia campus at Georgia Southern University Savannah, broke ground April 2026; opening 2028.",
        "key_specs": ["Dental education campus", "Georgia Southern Savannah", "Clinical and academic spaces"],
        "mentioned_brands": [],
        "competitor_watch": ["dental equipment", "lab casework", "HVAC", "medical gas", "flooring", "lighting"],
        "sources": [{"title": "Healthcare/education development coverage", "url": "https://www.beckershospitalreview.com/"}],
        "open_for": "Early construction — institutional and clinical specs open.",
    },
    {
        "id": "atrium-morehouse-teaching-hospital",
        "name": "Atrium Health / Morehouse Teaching Hospital",
        "city": "Atlanta",
        "county": "Fulton",
        "status": "planning",
        "project_type": "healthcare",
        "estimated_value_usd": 800000000,
        "square_footage": None,
        "owner": "Atrium Health + Morehouse School of Medicine",
        "architect": "",
        "general_contractor": "",
        "opened_or_announced_date": "2026-05-01",
        "description": "$800M teaching hospital proposal in southwest Atlanta with Morehouse School of Medicine. Pre-construction; completion not before 2029.",
        "key_specs": ["Teaching hospital", "$800M estimated", "Southwest Atlanta", "Morehouse partnership"],
        "mentioned_brands": [],
        "competitor_watch": ["medical equipment", "HVAC/lab air", "nurse call", "flooring", "doors and hardware", "fire/life safety"],
        "sources": [{"title": "Atlanta healthcare development coverage", "url": "https://www.ajc.com/"}],
        "open_for": "Proposal/planning — long-lead spec influence window open.",
    },
    {
        "id": "wellstar-columbia-county-medical",
        "name": "Wellstar Columbia County Medical Center",
        "city": "Grovetown",
        "county": "Columbia",
        "status": "under_construction",
        "project_type": "healthcare",
        "estimated_value_usd": 380000000,
        "square_footage": 340000,
        "owner": "Wellstar Health System",
        "architect": "",
        "general_contractor": "",
        "opened_or_announced_date": "2026-04-01",
        "description": "$380M+ hospital and 90,000 SF MOB at 5000 Gateway Blvd. Certificate of occupancy expected mid-2026; opening late summer 2026.",
        "key_specs": ["100 inpatient beds", "Level II trauma ED target", "90,000 SF MOB", "Surgical and cath/IR platform"],
        "mentioned_brands": [],
        "competitor_watch": ["medical equipment", "HVAC", "nurse call", "flooring", "doors/hardware", "fire/life safety"],
        "sources": [{"title": "Augusta Good News — Wellstar Columbia County", "url": "https://augustagoodnews.com/wellstar-columbia-county-medical-center-on-track-to-open-in-late-summer-2026/"}],
        "open_for": "Near completion — late add-ons and MOB tenant specs may remain.",
    },
]


def merge() -> dict:
    existing = json.loads(DATA.read_text())
    by_id = {p["id"]: p for p in existing["projects"]}

    for p in NEW_PROJECTS:
        if p["id"] in by_id:
            # enrich existing record
            cur = by_id[p["id"]]
            for k, v in p.items():
                if k == "sources" and cur.get("sources"):
                    cur["sources"] = p["sources"] + [s for s in cur["sources"] if s not in p["sources"]]
                elif v and (not cur.get(k) or cur.get(k) in ("", [], None)):
                    cur[k] = v
                elif k == "opened_or_announced_date":
                    cur[k] = v
        else:
            by_id[p["id"]] = p

    # Update PNK Griffin merge with old griffin-industrial-facility id
    if "griffin-industrial-facility" in by_id and "pnk-griffin-200" in by_id:
        old = by_id.pop("griffin-industrial-facility")
        merged = by_id["pnk-griffin-200"]
        if not merged.get("general_contractor") and old.get("general_contractor"):
            merged["general_contractor"] = old["general_contractor"]

    # Merge duplicate hospital ids
    if "columbia-county-hospital-mob" in by_id and "wellstar-columbia-county-medical" in by_id:
        by_id.pop("columbia-county-hospital-mob", None)

    projects = list(by_id.values())
    projects.sort(key=lambda p: (p.get("opened_or_announced_date") or "0000", p["name"]), reverse=True)

    recent = [
        p for p in projects
        if (p.get("opened_or_announced_date") or "") >= "2026-04-24"
    ]

    return {
        "generated_at": "2026-07-24",
        "geography": "Georgia, USA",
        "capture_method": "web research + Kimi seed, expanded Apr–Jul 2026 via Claude/Gemini-assisted curation",
        "date_range": "2026-04-24 to 2026-07-24 (last 3 months)",
        "projects": projects,
        "stats": {
            "total": len(projects),
            "opened_last_3_months": len(recent),
        },
        "notes": (
            f"Expanded corpus: {len(projects)} total projects, {len(recent)} with activity in the last 3 months "
            "(opened/announced/groundbroken/permitted since 2026-04-24). Sources include news, REBusinessOnline, "
            "BLDUP, city/county releases, and developer announcements. URLs verified where available; some legacy "
            "seed entries retain title-only sources pending URL backfill."
        ),
    }


def main() -> None:
    payload = merge()
    text = json.dumps(payload, indent=2) + "\n"
    DATA.write_text(text)
    PUBLIC.parent.mkdir(parents=True, exist_ok=True)
    PUBLIC.write_text(text)
    print(f"Wrote {payload['stats']['total']} projects ({payload['stats']['opened_last_3_months']} in last 3 months)")


if __name__ == "__main__":
    main()
